"use client";
import { useEffect, useState } from "react";
import type { CatalogCampaign, CatalogProduct } from "@/lib/catalog/types";

export default function Home() {
  const [campaigns, setCampaigns] = useState<CatalogCampaign[]>([]);
  const [picked, setPicked] = useState<CatalogProduct | null>(null);
  useEffect(() => { fetch("/api/catalog").then(r => r.ok ? r.json() as Promise<{ campaigns?: CatalogCampaign[] }> : { campaigns: [] }).then(x => setCampaigns(x.campaigns || [])); }, []);
  return <main className="min-h-screen bg-slate-100 p-5 text-slate-900"><div className="mx-auto max-w-5xl"><header className="mb-8"><p className="text-sm font-semibold text-blue-600">Bubble Up</p><h1 className="text-4xl font-bold">Меню</h1><p className="mt-2 text-slate-600">Каталог загружается из конструктора в реальном времени.</p></header>{campaigns.length === 0 ? <div className="rounded-2xl bg-white p-10 text-center shadow"><h2 className="text-xl font-semibold">Каталог пока пуст</h2><p className="mt-2 text-slate-500">Создайте первую акцию в конструкторе.</p><a className="mt-5 inline-block rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white" href="/admin">Открыть конструктор</a></div> : campaigns.filter(c => c.active).map(campaign => <section key={campaign.id} className="mb-10"><h2 className="mb-4 text-2xl font-bold">{campaign.name}</h2>{campaign.menus.map(menu => <div key={menu.id} className="mb-7"><h3 className="mb-3 text-lg font-semibold text-slate-700">{menu.name}</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{menu.products.map(product => <button key={product.id} onClick={() => setPicked(product)} className={`overflow-hidden rounded-2xl bg-white text-left shadow transition hover:-translate-y-1 ${product.is_main ? "sm:col-span-2 lg:col-span-3" : ""}`}><div className="h-48 bg-slate-200">{product.video_url ? <video className="h-full w-full object-cover" src={product.video_url} autoPlay muted loop playsInline /> : product.image_url ? <img className="h-full w-full object-cover" src={product.image_url} alt="" /> : <div className="grid h-full place-items-center text-slate-400">Нет медиа</div>}</div><div className="p-4"><h4 className="font-semibold">{product.name}</h4>{product.description && <p className="mt-1 text-sm text-slate-500">{product.description}</p>}<p className="mt-3 font-bold">{product.price} ₽</p></div></button>)}</div></div>)}</section>)}{picked && <div className="fixed inset-0 grid place-items-center bg-black/50 p-5" onClick={() => setPicked(null)}><div className="w-full max-w-lg rounded-2xl bg-white p-6" onClick={e => e.stopPropagation()}><h2 className="text-2xl font-bold">{picked.name}</h2><p className="mt-2 text-slate-600">{picked.details || picked.description || "Описание не добавлено"}</p><p className="mt-5 text-xl font-bold">{picked.price} ₽</p><button onClick={() => setPicked(null)} className="mt-6 rounded-xl bg-blue-600 px-5 py-3 text-white">Закрыть</button></div></div>}</div></main>;
}
