"use client";
import { useState } from "react";
import { ChevronDown, Gift, Home as HomeIcon, MapPin, MessageCircle, Plus, Search, ShoppingBag, Sparkles, UserRound, X } from "lucide-react";

const items = [
  ["Капучино", "с воздушной пенкой", "285", "☕", "from-[#d8a278] to-[#8d4f31]"],
  ["Матча латте", "нежная и сливочная", "365", "🍵", "from-[#b8ce77] to-[#55704a]"],
  ["Айс латте", "с ванильным сиропом", "325", "🧊", "from-[#c6dce4] to-[#62879a]"],
  ["Какао", "с маршмеллоу", "340", "🍫", "from-[#d6a57c] to-[#6b392e]"],
];

export default function Home() {
  const [picked, setPicked] = useState<typeof items[0] | null>(null);
  const [cart, setCart] = useState<typeof items[0][]>([]);
  const [pay, setPay] = useState(false);
  const total = cart.reduce((sum, item) => sum + Number(item[2]), 0);
  return <main className="min-h-screen bg-[#101212] text-[#f8f6f0]"><div className="mx-auto min-h-screen max-w-[620px] bg-[#171a19] pb-24 shadow-2xl">
    <header className="sticky top-0 z-20 flex items-center justify-between border-b border-white/10 bg-[#171a19]/95 px-5 py-4 backdrop-blur-xl"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#d7f36b] text-xl text-[#182018]">🐳</div><div><b className="text-sm">drinkit</b><button className="flex items-center gap-1 text-xs text-white/50"><MapPin size={12}/> Ленинская, 1 <ChevronDown size={12}/></button></div></div><div className="flex gap-2"><button className="grid h-10 w-10 place-items-center rounded-full bg-white/6"><Search size={17}/></button><button className="grid h-10 w-10 place-items-center rounded-full bg-white/6"><UserRound size={18}/></button></div></header>
    <section className="px-5 pb-2 pt-7"><p className="mb-1 text-sm text-[#d7f36b]">Добрый вечер, Михаил</p><div className="mb-5 flex items-end justify-between"><h1 className="text-3xl font-semibold tracking-tight">Что закажем?</h1><button className="text-sm text-white/50">История</button></div><div className="flex gap-2 overflow-x-auto scrollbar-none">{["Популярное", "Кофе", "Еда", "Для тебя"].map((x, i) => <button key={x} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${i === 0 ? "bg-[#d7f36b] text-[#182018]" : "bg-white/6 text-white/60"}`}>{x}</button>)}</div></section>
    <section className="space-y-4 px-4 py-5">{items.map((item) => <article key={item[0]} className="overflow-hidden rounded-[28px] border border-white/10 bg-[#202523]"><div className={`grid h-64 place-items-center bg-gradient-to-br ${item[4]}`}><span className="text-9xl drop-shadow-2xl">{item[3]}</span></div><div className="flex items-center justify-between p-5"><div><h2 className="text-lg font-medium">{item[0]}</h2><p className="mt-1 text-sm text-white/50">{item[1]}</p><p className="mt-3 text-lg font-semibold">от {item[2]} ₽</p></div><button onClick={() => setPicked(item)} className="grid h-12 w-12 place-items-center rounded-full bg-[#d7f36b] text-[#172015]"><Plus size={23}/></button></div></article>)}</section>
    <section className="mx-4 mb-6 rounded-[28px] border border-[#d7f36b]/20 bg-[#222b24] p-5"><div className="flex justify-between"><div><div className="mb-2 flex items-center gap-2 text-[#d7f36b]"><Sparkles size={16}/><span className="text-xs font-semibold uppercase tracking-[.15em]">Drinkit Lab</span></div><h2 className="text-xl font-medium">Придумай напиток словами</h2><p className="mt-1 text-sm text-white/55">«ягодное, не очень сладкое, со льдом»</p></div><MessageCircle className="text-[#d7f36b]" size={27}/></div><button className="mt-5 rounded-full bg-[#d7f36b] px-5 py-3 text-sm font-semibold text-[#172015]">Попробовать ИИ-рецепт</button></section>
    <nav className="fixed bottom-0 left-1/2 z-20 flex w-full max-w-[620px] -translate-x-1/2 justify-around border-t border-white/10 bg-[#171a19]/95 px-5 py-3 text-xs text-white/45 backdrop-blur-xl"><button className="flex flex-col items-center gap-1 text-[#d7f36b]"><HomeIcon size={19}/>Главная</button><button className="flex flex-col items-center gap-1"><Gift size={19}/>Бонусы</button><button className="flex flex-col items-center gap-1"><ShoppingBag size={19}/>Заказы</button><button className="flex flex-col items-center gap-1"><UserRound size={19}/>Профиль</button></nav>
    {cart.length > 0 && <button onClick={() => setPay(true)} className="fixed bottom-[78px] left-1/2 z-30 flex w-[min(480px,calc(100%-32px))] -translate-x-1/2 justify-between rounded-2xl bg-[#d7f36b] px-5 py-4 font-semibold text-[#172015] shadow-2xl"><span><ShoppingBag className="mr-2 inline" size={19}/> {cart.length} напитка</span><span>{total} ₽ →</span></button>}
    {picked && <div className="fixed inset-0 z-40 grid place-items-end bg-black/70 sm:place-items-center sm:p-5"><div className="w-full max-w-lg rounded-t-[30px] bg-[#202523] p-6 sm:rounded-[30px]"><div className="mb-5 flex justify-between"><div><p className="text-xs uppercase tracking-[.15em] text-white/45">Настроить напиток</p><h2 className="mt-1 text-2xl font-semibold">{picked[0]}</h2></div><button onClick={() => setPicked(null)}><X/></button></div><div className={`mb-6 grid h-40 place-items-center rounded-2xl bg-gradient-to-br ${picked[4]}`}><span className="text-7xl">{picked[3]}</span></div><button onClick={() => { setCart([...cart, picked]); setPicked(null); }} className="flex w-full justify-between rounded-2xl bg-[#d7f36b] px-5 py-4 font-semibold text-[#172015]"><span>Добавить в корзину</span><span>{picked[2]} ₽</span></button></div></div>}
    {pay && <div className="fixed inset-0 z-40 grid place-items-end bg-black/70 sm:place-items-center sm:p-5"><div className="w-full max-w-md rounded-t-[30px] bg-[#202523] p-6 sm:rounded-[30px]"><div className="mb-6 flex justify-between"><div><p className="text-xs uppercase tracking-[.15em] text-white/45">Заказ №1048</p><h2 className="mt-1 text-2xl font-semibold">Оплата заказа</h2></div><button onClick={() => setPay(false)}><X/></button></div><div className="mb-5 flex justify-between rounded-2xl bg-white/5 p-4"><span>К оплате</span><b>{total} ₽</b></div><button className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#229ED9] py-4 font-semibold"><MessageCircle size={20}/> Оплатить через Telegram</button><button className="mt-4 w-full text-xs text-white/40 underline">Не получается через Telegram? Оплатить через СБП</button></div></div>}
  </div></main>;
}
