-- Remove accidental PUBLIC/anon execution from authenticated application RPCs.
revoke all on function public.calculate_employee_payroll_period(uuid, date) from public, anon;
revoke all on function public.admin_update_employee_account(uuid, text, text, text, text, text, uuid, employee_status, boolean, text) from public, anon;
revoke all on function public.admin_set_employee_role(uuid, user_role_code) from public, anon;
revoke all on function public.admin_delete_employee(uuid) from public, anon;
revoke all on function public.admin_replace_employee_store_assignments(uuid, uuid[]) from public, anon;
revoke all on function public.admin_list_accessible_stores() from public, anon;
revoke all on function public.admin_restore_employee(uuid) from public, anon;
revoke all on function public.admin_archive_store(uuid) from public, anon;
revoke all on function public.admin_restore_store(uuid) from public, anon;
revoke all on function public.admin_create_employee_account(uuid, text, text, text, text, text, uuid, employee_status, user_role_code, uuid[]) from public, anon;
revoke all on function public.send_city_warehouse_managers_notification(text, text, text, text, text, uuid) from public, anon;
revoke all on function public.academy_start_lesson(uuid) from public, anon;
revoke all on function public.academy_complete_lesson(uuid) from public, anon;
revoke all on function public.academy_get_assessment_payload(uuid) from public, anon;
revoke all on function public.academy_start_assessment(uuid) from public, anon;
revoke all on function public.academy_submit_assessment(uuid, jsonb) from public, anon;
revoke all on function public.save_day_routine_template(uuid, text, text, jsonb) from public, anon;
revoke all on function public.toggle_day_routine_item_completion(uuid, text, uuid, boolean) from public, anon;
revoke all on function public.run_day_routine_evening_reminders(timestamptz) from public, anon;
revoke all on function public.list_push_notification_targets(text, text, uuid, uuid, integer) from public, anon;
revoke all on function public.push_notification_targets_rpc(text, text, uuid, uuid, integer) from public, anon;
revoke all on function public.record_push_delivery(uuid, notification_delivery_status, text) from public, anon;
revoke all on function public.deactivate_push_subscription(uuid, text) from public, anon;
revoke all on function public.save_day_routine_item_settings(uuid, jsonb) from public, anon;

grant execute on function public.calculate_employee_payroll_period(uuid, date) to authenticated;
grant execute on function public.admin_update_employee_account(uuid, text, text, text, text, text, uuid, employee_status, boolean, text) to authenticated;
grant execute on function public.admin_set_employee_role(uuid, user_role_code) to authenticated;
grant execute on function public.admin_delete_employee(uuid) to authenticated;
grant execute on function public.admin_replace_employee_store_assignments(uuid, uuid[]) to authenticated;
grant execute on function public.admin_list_accessible_stores() to authenticated;
grant execute on function public.admin_restore_employee(uuid) to authenticated;
grant execute on function public.admin_archive_store(uuid) to authenticated;
grant execute on function public.admin_restore_store(uuid) to authenticated;
grant execute on function public.admin_create_employee_account(uuid, text, text, text, text, text, uuid, employee_status, user_role_code, uuid[]) to authenticated;
grant execute on function public.send_city_warehouse_managers_notification(text, text, text, text, text, uuid) to authenticated;
grant execute on function public.academy_start_lesson(uuid) to authenticated;
grant execute on function public.academy_complete_lesson(uuid) to authenticated;
grant execute on function public.academy_get_assessment_payload(uuid) to authenticated;
grant execute on function public.academy_start_assessment(uuid) to authenticated;
grant execute on function public.academy_submit_assessment(uuid, jsonb) to authenticated;
grant execute on function public.save_day_routine_template(uuid, text, text, jsonb) to authenticated;
grant execute on function public.toggle_day_routine_item_completion(uuid, text, uuid, boolean) to authenticated;
grant execute on function public.run_day_routine_evening_reminders(timestamptz) to authenticated;
grant execute on function public.list_push_notification_targets(text, text, uuid, uuid, integer) to authenticated;
grant execute on function public.push_notification_targets_rpc(text, text, uuid, uuid, integer) to authenticated;
grant execute on function public.record_push_delivery(uuid, notification_delivery_status, text) to authenticated;
grant execute on function public.deactivate_push_subscription(uuid, text) to authenticated;
grant execute on function public.save_day_routine_item_settings(uuid, jsonb) to authenticated;

-- These are database test helpers and must not be exposed through PostgREST.
revoke all on function public.test_many_cols_sd() from public, anon, authenticated;
revoke all on function public.test_join() from public, anon, authenticated;
revoke all on function public.test_join_filter3() from public, anon, authenticated;
revoke all on function public.test_time_filter() from public, anon, authenticated;
revoke all on function public.test_nd_join() from public, anon, authenticated;
revoke all on function public.test_delivery_join_ok() from public, anon, authenticated;
revoke all on function public.test_many_params_many_cols_query11(text, text, uuid, uuid, integer) from public, anon, authenticated;
revoke all on function public.test_since_minutes_sd(integer) from public, anon, authenticated;
revoke all on function public.test_setof_view_sd() from public, anon, authenticated;
revoke all on function public.test_setof_view_filter_sd(text) from public, anon, authenticated;
revoke all on function public.test_setof_view_since(integer) from public, anon, authenticated;
revoke all on function public.test_setof_view_filters2(text, integer) from public, anon, authenticated;
revoke all on function public.test_setof_view_filters3(text, text, integer) from public, anon, authenticated;
revoke all on function public.test_setof_view_filters4(text, text, uuid, uuid, integer) from public, anon, authenticated;
